// questionsTypes.js
export const questionsTypes = {
  FETCH_ALL_QUESTIONS: "FETCH_ALL_QUESTIONS",
  ADD_NEW_QUESTION: "ADD_NEW_QUESTION",
  DELETE_QUESTION: "DELETE_QUESTION",
  LOAD_QUESTION_LOADING: "LOAD_QUESTION_LOADING",
};
